// Runs the clocktest CPU kernels natively, writing their expected results:
// gen_expected > expected.h
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "kernels.c"
#include "seeds.h"

int main(void) {
    static uint32_t scratch[KERNEL_SCRATCH / 4];
    uint32_t (*const kernels[])(uint32_t, uint32_t *) = { k_crc, k_mul, k_div, k_sort, k_interp, k_mem };
    int count = sizeof(kernels) / sizeof(kernels[0]);
    printf("// Generated by gen_expected.c: expected[kernel][seed].\n");
    printf("static const uint32_t expected[%d][NUM_SEEDS] = {\n", count);
    for (int k = 0; k < count; k++) {
        printf("    {");
        for (int s = 0; s < NUM_SEEDS; s++) printf(" 0x%08xu,", kernels[k](seed_of(s), scratch));
        printf(" },\n");
    }
    printf("};\n");
    return 0;
}
